"""Production seed scenarios and templates for organizational project setup."""

CANONICAL_TASKS = [
    {
        "key": "T1",
        "title": "Set up project repository",
        "description": "Initialize Git repository, configure .gitignore, branch protection and CI workflow.",
        "column_status": "done",
        "duration_days": 1,
        "depends_on": [],
    },
    {
        "key": "T2",
        "title": "Design database schema",
        "description": "Draft relational models for tasks and dependencies. Prepare migrations and indices.",
        "column_status": "done",
        "duration_days": 2,
        "depends_on": ["T1"],
    },
    {
        "key": "T3",
        "title": "Build backend API",
        "description": "Implement FastAPI routes, graph recomputation, cycle check, and CPM scheduler.",
        "column_status": "in_progress",
        "duration_days": 4,
        "depends_on": ["T2"],
    },
    {
        "key": "T4",
        "title": "Build authentication service",
        "description": "Set up token validation, user credentials, and session handlers.",
        "column_status": "backlog",
        "duration_days": 3,
        "depends_on": ["T2"],
    },
    {
        "key": "T5",
        "title": "Build frontend UI shell",
        "description": "Create React + Vite application, configure modern styling, themes and columns.",
        "column_status": "in_progress",
        "duration_days": 3,
        "depends_on": ["T1"],
    },
    {
        "key": "T6",
        "title": "Integrate frontend with API",
        "description": "Connect Kanban drag-and-drop to PATCH endpoints and TanStack Query state cache.",
        "column_status": "backlog",
        "duration_days": 2,
        "depends_on": ["T3", "T5"],
    },
    {
        "key": "T7",
        "title": "Integration tests",
        "description": "End-to-end integration tests for cycle rejection, diamond convergence, and rollback.",
        "column_status": "backlog",
        "duration_days": 2,
        "depends_on": ["T3", "T4"],
    },
    {
        "key": "T8",
        "title": "Write API documentation",
        "description": "Document OpenAPI schema, explain max() vs sum() algorithm and deployment steps.",
        "column_status": "backlog",
        "duration_days": 1,
        "depends_on": ["T3"],
    },
    {
        "key": "T9",
        "title": "Deploy to staging",
        "description": "Containerize backend, configure Render/Neon Postgres, deploy frontend to Vercel.",
        "column_status": "backlog",
        "duration_days": 1,
        "depends_on": ["T6", "T7"],
    },
    {
        "key": "T10",
        "title": "Demo preparation",
        "description": "Prepare walkthrough scenario showcasing cycle detection, delay propagation, and AI suggestions.",
        "column_status": "backlog",
        "duration_days": 1,
        "depends_on": ["T9"],
    },
]

# Alias for backward compatibility
SEED_TASKS = CANONICAL_TASKS

FINTECH_TASKS = [
    {
        "key": "F1",
        "title": "Define PCI-DSS compliance specifications",
        "description": "Document encryption, vault storage, and audit logging standards for payment data.",
        "column_status": "done",
        "duration_days": 2,
        "depends_on": [],
    },
    {
        "key": "F2",
        "title": "Implement credit card tokenization vault",
        "description": "Zero-knowledge token storage with AES-256 GCM encryption keys in AWS KMS.",
        "column_status": "done",
        "duration_days": 3,
        "depends_on": ["F1"],
    },
    {
        "key": "F3",
        "title": "Build payment processing gateway API",
        "description": "Implement Stripe and Adyen webhook listeners and idempotent charge settlement.",
        "column_status": "in_progress",
        "duration_days": 4,
        "depends_on": ["F2"],
    },
    {
        "key": "F4",
        "title": "Implement KYC and anti-fraud filters",
        "description": "Integrate Persona / Onfido identity verification and velocity limit rules.",
        "column_status": "in_progress",
        "duration_days": 3,
        "depends_on": ["F1"],
    },
    {
        "key": "F5",
        "title": "Build customer checkout web interface",
        "description": "Responsive React checkout form with biometric Apple Pay & Google Pay support.",
        "column_status": "backlog",
        "duration_days": 3,
        "depends_on": ["F3"],
    },
    {
        "key": "F6",
        "title": "Penetration testing & third-party audit",
        "description": "Simulate card skimming, SQL injection, and authorization bypass vulnerabilities.",
        "column_status": "backlog",
        "duration_days": 3,
        "depends_on": ["F3", "F4"],
    },
    {
        "key": "F7",
        "title": "Banking partner sandbox certification",
        "description": "Run 500 synthetic settlement transactions against Chase Paymentech test sandbox.",
        "column_status": "backlog",
        "duration_days": 2,
        "depends_on": ["F5", "F6"],
    },
    {
        "key": "F8",
        "title": "Production financial launch",
        "description": "Enable live merchant transactions with 24/7 on-call incident response coverage.",
        "column_status": "backlog",
        "duration_days": 1,
        "depends_on": ["F7"],
    },
]

AI_PIPELINE_TASKS = [
    {
        "key": "A1",
        "title": "Select LLM architecture & benchmark inference latency",
        "description": "Compare throughput, token cost, and context length between Groq LLaMA and OpenAI models.",
        "column_status": "done",
        "duration_days": 2,
        "depends_on": [],
    },
    {
        "key": "A2",
        "title": "Set up vector database cluster (Qdrant / pgvector)",
        "description": "Provision distributed vector indices with HNSW cosine similarity search.",
        "column_status": "done",
        "duration_days": 2,
        "depends_on": ["A1"],
    },
    {
        "key": "A3",
        "title": "Build document ingestion & semantic chunking pipeline",
        "description": "Parse PDFs, Markdown, and API docs with recursive text splitter and metadata tags.",
        "column_status": "in_progress",
        "duration_days": 3,
        "depends_on": ["A2"],
    },
    {
        "key": "A4",
        "title": "Implement RAG retrieval with hybrid re-ranking",
        "description": "BM25 keyword search blended with Cohere cross-encoder reranking.",
        "column_status": "backlog",
        "duration_days": 3,
        "depends_on": ["A3"],
    },
    {
        "key": "A5",
        "title": "Implement multi-agent supervisor graph",
        "description": "Deterministic LangGraph execution flow with loop protection and budget caps.",
        "column_status": "backlog",
        "duration_days": 4,
        "depends_on": ["A1", "A3"],
    },
    {
        "key": "A6",
        "title": "Deploy guardrail filters & prompt injection firewall",
        "description": "Llama Guard 3 safety classifier to sanitize adversarial prompt injections.",
        "column_status": "backlog",
        "duration_days": 2,
        "depends_on": ["A4", "A5"],
    },
    {
        "key": "A7",
        "title": "End-to-end evaluation with Ragas & TruLens",
        "description": "Run golden dataset benchmark for faithfulness, answer relevance, and context recall.",
        "column_status": "backlog",
        "duration_days": 2,
        "depends_on": ["A6"],
    },
    {
        "key": "A8",
        "title": "Production rollout & streaming API deployment",
        "description": "Expose Server-Sent Events (SSE) streaming API with Redis rate limiting.",
        "column_status": "backlog",
        "duration_days": 1,
        "depends_on": ["A7"],
    },
]

PROJECT_TEMPLATES = {
    "canonical": {
        "id": "canonical",
        "name": "Canonical Contata Benchmark (10 Tasks)",
        "description": "Dual diamond convergence benchmark testing CPM, schedule propagation, and cycle rejection.",
        "tasks": CANONICAL_TASKS,
    },
    "fintech": {
        "id": "fintech",
        "name": "Fintech Payment Gateway & PCI Compliance (8 Tasks)",
        "description": "Real-world financial engineering: KMS vault, tokenization, fraud checks, and banking audit.",
        "tasks": FINTECH_TASKS,
    },
    "ai_pipeline": {
        "id": "ai_pipeline",
        "name": "Enterprise Multi-Agent RAG Platform (8 Tasks)",
        "description": "Vector indexing, hybrid re-ranking, supervisor graphs, and guardrail safety pipelines.",
        "tasks": AI_PIPELINE_TASKS,
    },
    "blank": {
        "id": "blank",
        "name": "Blank Organization Workspace",
        "description": "Empty workspace for your team to build custom tasks from scratch.",
        "tasks": [],
    },
}
